In [1]:
import pandas as pd

In [4]:
data = pd.Series([1,2,3,5])

In [7]:
data[3] = 4

In [8]:
data

0    1
1    2
2    3
3    4
dtype: int64

In [15]:
data1 = ({
    'name' : ["Umesh","prince","nitin","vikas"],
    'english' :[20,19,18,11],
    'math' : [29,21,19,10]
})

In [41]:

data1 =pd.DataFrame(data1)
data1.head()

     name  english  math  totol
0   Umesh       20    29     49
1  prince       19    21     40
2   nitin       18    19     37
3   vikas       11    10     21

In [44]:
data1['totol'] = data1['math'] + data1['english']
data1['average'] = data1['totol']/2
data1

     name  english  math  totol  average
0   Umesh       20    29     49     24.5
1  prince       19    21     40     20.0
2   nitin       18    19     37     18.5
3   vikas       11    10     21     10.5