In [2]:
import pandas as pd
import numpy as np

data = {
    "name": ["Umesh", "Prince", "Vikas", "Rohit", "Aman", "Neha"],
    "math": [85, np.nan, 92, 70, 88, 95],
    "english": [80, 75, 90, 85,np.nan, 93],
    "hindi": [82, 79, 88, np.nan, 84, 91]
}

In [3]:
df = pd.DataFrame(data)

In [6]:
df.head()

     name  math  english  hindi
0   Umesh    85       80     82
1  Prince    78       75     79
2   Vikas    92       90     88
3   Rohit    70       65     60
4    Aman    88       85     84

In [10]:
df.head(3)

     name  math  english  hindi
0   Umesh    85       80     82
1  Prince    78       75     79
2   Vikas    92       90     88

In [12]:
df.tail()

     name  math  english  hindi
1  Prince    78       75     79
2   Vikas    92       90     88
3   Rohit    70       65     60
4    Aman    88       85     84
5    Neha    95       93     91

In [14]:
df.tail(2)

   name  math  english  hindi
4  Aman    88       85     84
5  Neha    95       93     91

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     6 non-null      str
 1   math     6 non-null      int64
 2   english  6 non-null      int64
 3   hindi    6 non-null      int64
dtypes: int64(3), str(1)
memory usage: 353.0 bytes

In [18]:
df.describe()

            math    english      hindi
count   6.000000   6.000000   6.000000
mean   84.666667  81.333333  80.666667
std     9.287985  10.327956  10.984838
min    70.000000  65.000000  60.000000
25%    79.750000  76.250000  79.750000
50%    86.500000  82.500000  83.000000
75%    91.000000  88.750000  87.000000
max    95.000000  93.000000  91.000000

In [20]:
df["math"].value_counts()

math
85    1
78    1
92    1
70    1
88    1
95    1
Name: count, dtype: int64

In [22]:
df["name"].unique()

<ArrowStringArray>
['Umesh', 'Prince', 'Vikas', 'Rohit', 'Aman', 'Neha']
Length: 6, dtype: str

In [28]:

df.dropna()

    name  math  english  hindi
0  Umesh  85.0     80.0   82.0
2  Vikas  92.0     90.0   88.0
5   Neha  95.0     93.0   91.0

In [30]:
df.isna()

    name   math  english  hindi
0  False  False    False  False
1  False   True    False  False
2  False  False    False  False
3  False  False    False   True
4  False  False     True  False
5  False  False    False  False

In [31]:
df.fillna(3)

     name  math  english  hindi
0   Umesh  85.0     80.0   82.0
1  Prince   3.0     75.0   79.0
2   Vikas  92.0     90.0   88.0
3   Rohit  70.0     85.0    3.0
4    Aman  88.0      3.0   84.0
5    Neha  95.0     93.0   91.0

In [1]:
import pandas as pd

data = {
    "name": ["Umesh", "Prince", "Vikas", "Rohit", "Aman", "Neha"],
    "math": [85, 78, 92, 70, 88, 95],
    "english": [80, 75, 90, 65, 85, 93]
}

df = pd.DataFrame(data)

In [3]:
df["total"] = df["math"] + df["english"]

In [4]:
df

     name  math  english  total
0   Umesh    85       80    165
1  Prince    78       75    153
2   Vikas    92       90    182
3   Rohit    70       65    135
4    Aman    88       85    173
5    Neha    95       93    188

In [19]:
df["result"] = df["total"].apply(lambda x: "pass" if x >= 100 else "fail")

In [20]:
df

     name  math  english  total result grade
0   Umesh    85       80    165   pass     b
1  Prince    78       75    153   pass     b
2   Vikas    92       90    182   pass     a
3   Rohit    70       65    135   pass     c
4    Aman    88       85    173   pass     a
5    Neha    95       93    188   pass     a

In [5]:
 df.corr(["math"],["english"])

ValueError: could not convert string to float: 'Umesh'

In [17]:
df

     name  math  english  total result grade
0   Umesh    85       80    165   fail     b
1  Prince    78       75    153   fail     b
2   Vikas    92       90    182   pass     a
3   Rohit    70       65    135   fail     c
4    Aman    88       85    173   pass     a
5    Neha    95       93    188   pass     a