In [3]:
import pandas as pd

In [4]:
data = {
    "name":["umesh","prashant","dubey","prince"],
    "math":[25,20,25,22],
    "english":[12,25,13,14]
}
data1 = pd.DataFrame(data)

In [14]:
data1.iloc[0:2,1:3]

   math  english
0    25       12
1    20       25

In [38]:
data1.loc[0:2,["math","english"]]

   math  english
0    25       12
1    20       25
2    25       13